export const COURT_TYPES = [
  "CHILDRENS COURT",
  "MAGISTRATES COURT",
  "COUNTY COURT",
  "SUPREME COURT",
  "COURT OF APPEAL",
  "HIGH COURT",
  "OFFICE OF CHIEF EXAMINER",
  "OTHER"
];

export const COURT_LOCATIONS = [
  "BROADMEADOWS", "DANDENONG", "FRANKSTON", "HEIDELBERG", "MELBOURNE",
  "MOORABBIN JUSTICE CENTRE", "NEIGHBOURHOOD JUSTICE CENTRE", "RINGWOOD",
  "SUNSHINE", "WERRIBEE", "REGIONAL LOCATION"
];

export const REGIONAL_LOCATIONS = [
  "ARARAT", "BACCHUS MARSH", "BAIRNSDALE", "BALLARAT", "BENALLA", "BENDIGO",
  "CASTLEMAINE", "COBRAM", "COLAC", "CORRYONG", "DROMANA", "ECHUCA",
  "EDENHOPE", "GEELONG", "HAMILTON", "HOPETOUN", "HORSHAM", "KERANG",
  "KORUMBURRA", "KYNETON", "LATROBE VALLEY", "MANSFIELD", "MARYBOROUGH",
  "MILDURA", "MYRTLEFORD", "NHILL", "OMEO", "ORBOST", "OUYEN", "PORTLAND",
  "ROBINVALE", "SALE", "SEYMOUR", "SHEPPARTON", "ST ARNAUD", "STAWELL",
  "SWAN HILL", "WANGARATTA", "WARRNAMBOOL", "WODONGA", "WONTHAGGI"
];

export const PROSECUTION_LIST = [
  "VICTORIA POLICE", "OFFICE OF PUBLIC PROSECUTION",
  "COMMONWEALTH DEPARTMENT PUBLIC PROSECUTION", "FINES VICTORIA",
  "DEPARTMENT OF JUSTICE AND COMMUNITY SAFETY", "CORRECTIONS VICTORIA",
  "AUSTRALIAN FEDERAL POLICE", "VIC ROADS", "TAC",
  "VICTORIAN GOVERNMENT SOLICITORS OFFICE", "CHEIF EXAMINER",
  "COMMISSIONER OF POLICE", "LOCAL COUNCIL", "ATO", "OTHER"
];

export const LOCAL_COUNCILS = [
  "ALPINE SHIRE COUNCIL", "ARARAT RURAL CITY COUNCIL", "BALLARAT CITY COUNCIL",
  "BANYULE CITY COUNCIL", "BASS COAST SHIRE COUNCIL", "BAW BAW SHIRE COUNCIL",
  "BAYSIDE CITY COUNCIL", "BENALLA RURAL CITY COUNCIL", "BOROONDARA CITY COUNCIL",
  "BOROUGH OF QUEENSCLIFFE COUNCIL", "BRIMBANK CITY COUNCIL", "BULOKE SHIRE COUNCIL",
  "CAMPASPE SHIRE COUNCIL", "CARDINIA SHIRE COUNCIL", "CASEY CITY COUNCIL",
  "CENTRAL GOLDFIELDS SHIRE COUNCIL", "COLAC OTWAY SHIRE COUNCIL",
  "CORANGAMITE SHIRE COUNCIL", "DAREBIN CITY COUNCIL",
  "EAST GIPPSLAND SHIRE COUNCIL", "FRANKSTON CITY COUNCIL",
  "GANNAWARRA SHIRE COUNCIL", "GLEN EIRA CITY COUNCIL", "GLENELG SHIRE COUNCIL",
  "GOLDEN PLAINS SHIRE COUNCIL", "GREATER BENDIGO CITY COUNCIL",
  "GREATER DANDENONG CITY COUNCIL", "GREATER GEELONG CITY COUNCIL",
  "GREATER SHEPPARTON CITY COUNCIL", "HEPBURN SHIRE COUNCIL",
  "HINDMARSH SHIRE COUNCIL", "HOBSONS BAY CITY COUNCIL",
  "HORSHAM RURAL CITY COUNCIL", "HUME CITY COUNCIL", "INDIGO SHIRE COUNCIL",
  "KINGSTON CITY COUNCIL", "KNOX CITY COUNCIL", "LATROBE CITY COUNCIL",
  "LODDON SHIRE COUNCIL", "MACEDON RANGES SHIRE COUNCIL",
  "MANNINGHAM CITY COUNCIL", "MANSFIELD SHIRE COUNCIL",
  "MARIBYRNONG CITY COUNCIL", "MAROONDAH CITY COUNCIL", "MELBOURNE CITY COUNCIL",
  "MELTON CITY COUNCIL", "MERRI-BEK CITY COUNCIL", "MILDURA RURAL CITY COUNCIL",
  "MITCHELL SHIRE COUNCIL", "MOIRA SHIRE COUNCIL", "MONASH CITY COUNCIL",
  "MOONEE VALLEY CITY COUNCIL", "MOORABOOL SHIRE COUNCIL",
  "MORNINGTON PENINSULA SHIRE COUNCIL", "MOUNT ALEXANDER SHIRE COUNCIL",
  "MOYNE SHIRE COUNCIL", "MURRINDINDI SHIRE COUNCIL", "NILLUMBIK SHIRE COUNCIL",
  "NORTHERN GRAMPIANS SHIRE COUNCIL", "PORT PHILLIP CITY COUNCIL",
  "PYRENEES SHIRE COUNCIL", "SOUTH GIPPSLAND SHIRE COUNCIL",
  "SOUTHERN GRAMPIANS SHIRE COUNCIL", "STONNINGTON CITY COUNCIL",
  "STRATHBOGIE SHIRE COUNCIL", "SURF COAST SHIRE COUNCIL",
  "SWAN HILL RURAL CITY COUNCIL", "TOWONG SHIRE COUNCIL",
  "WANGARATTA RURAL CITY COUNCIL", "WARRNAMBOOL CITY COUNCIL",
  "WELLINGTON SHIRE COUNCIL", "WEST WIMMERA SHIRE COUNCIL",
  "WHITEHORSE CITY COUNCIL", "WHITTLESEA CITY COUNCIL", "WODONGA CITY COUNCIL",
  "WYNDHAM CITY COUNCIL", "YARRA CITY COUNCIL", "YARRA RANGES SHIRE COUNCIL",
  "YARRIAMBIACK SHIRE COUNCIL"
];

export const CIRCUIT_FEES = [
  "Committals", "Bail - County Court", "Bail - Supreme Court",
  "Plea - County Court", "Plea - Supreme Court", "Appeal - County Court",
  "Trial - County Court", "Trial - Supreme Court", "Solicitor out of office"
];

export const COUNSEL_LEVELS = [
  "Senior Counsel", "Senior Junior Counsel", "Junior Counsel/Trial Counsel Development Program"
];

export const CLERKS = [
  "List A Barristers",
  "Greens List",
  "Foley's List",
  "Holmes List",
  "Lennon's List",
  "List G Barristers",
  "Gorman Chambers",
  "Douglas Menzies Chambers",
  "Aickin Chambers",
  "Selborne Chambers",
  "New Chambers",
  "Owen Dixon Chambers",
];

export const COUNSEL_BY_CLERK = {
  "List A Barristers": [
    "Priyanka Banerjee", "Katherine O'Byrne", "Samuel Hamilton Lindsay", "Dr Georgie Clough",
    "Rohan Nanthakumar", "Katherine France", "Selena Bateman", "Beatrice Paull", "Ben Kelly",
    "Andrew Belyea-Tate", "Marcel Delany", "Matthew Harding", "Nuwan Dias", "Jennifer Vogan",
    "Conor O'Beirne", "Georgia Dobbyn", "Gary Zhang", "Stephanie Mann", "Tom Diaz",
    "Luke Chircop", "Bernice Chen", "Angela Kittikhoun", "Anesti Petridis", "Jessica Elliott",
    "Dr Laura Schuijers", "Marcus Roberts", "David Heaton", "Elodie Nadon", "Tom Ellicott",
    "Yanni Goutzamanis", "Angus Willoughby", "Melinda Jackson", "Jakub Patela", "Andy Hanna",
    "Alissa Crittenden", "Laila Hamzi", "Elizabeth Brumby", "Jack Maxwell", "Madeleine Salinger",
    "Julia Nikolic", "Katharine Brown", "Ahmed Terzic", "Shawn Rajanayagam", "Sophie Molyneux",
    "Nicholas Baum", "Jacqui Fumberger", "Nicholas Petrie", "Sahrah Hogan", "Alexander Di Stefano",
    "Anna Batrouney", "Jessica Moir", "Ben Bromberg", "Tessa Meyrick", "Thomas Wood",
    "Simon Frauenfelder", "Glyn Ayres", "Alexandra Guild", "Rachel Amamoo", "Ella Delany",
    "Joel Phillips", "Karan Raghavan", "Caroline Dawes", "Paul Annabell", "Andrew Roe",
    "Jordan Wright", "Doug Porteous", "Claire Horan", "Vicki Bell", "Alexia Staker",
    "Alice Muhlebach", "Andrew McRobert", "Tim Farhall", "Fiona Hudgson", "William Newland",
    "Xuelin Teo", "Anna Lord", "Tim Jeffrie", "Adam Purton", "Stephanie Hooper",
    "Franceska Leoncio", "Roshan Chaile", "Mark Hosking", "Roman Rozenberg", "Geoffrey Kozminsky",
    "Olaf Ciolek", "Raini Zambelli", "Timothy Goodwin", "Georgie Coleman", "Tim Chalke",
    "Emma Murphy", "Matthew Minucci", "Christopher Tran", "Timothy Maxwell", "Julia Watson",
    "Dimitri Ternovski", "Daniel Snyder", "Andrew Barraclough", "Katherine Brazenor", "Brian Mason",
    "Simona Gory", "Leana Papaelia", "Fiona Batten", "Caryn van Proctor", "Helen Tiplady",
    "Nasos Kaskani", "Dr Philip Bender", "Rodrigo Pintos-Lopez", "Eloise Dias", "Michael Kingston",
    "St. John Hibble", "Chris Sievers", "Peter Nicholas", "Chrissy Mavroudis", "Anthony Lang",
    "Garrie Moloney", "Warren Mosley", "Joseph Tsalanidis", "Robert Strong", "Peter Best",
    "John Mattin", "Robert Williams SC", "Siobhan Kelly SC", "Premala Thiagarajan SC",
    "Kylie Evans KC", "Barnaby Chessell SC", "Christopher Brown KC", "Tamieka Spencer Bruce SC",
    "Paul Liondas KC", "Zoe Maud SC", "Emrys Nekvapil SC", "Mark Costello KC", "Frances Gordon KC",
    "Sam Rosewarne KC", "Albert Dinelli KC", "Carl Möller SC", "Nicholas Wood SC", "Emily Porter SC",
    "Dr Charles Parkinson KC", "Marc Felman KC", "Sandro Goubran KC", "Daniel McInerney KC",
    "Jonathon Redwood SC", "Dr Paul Vout KC", "Justin Graham KC", "Dr Oren Bigos KC",
    "Renée Enbom KC", "Christopher Young KC", "Dr Michael Rush KC", "Christopher Archibald KC",
    "Lisa De Ferrari SC", "Dr Andrew Hanak KC", "Stephen Parmenter KC", "Michael Borsky KC",
    "Dan Star KC", "Andrew McClelland KC", "Lachlan Armstrong KC", "Jason Pizer SC",
    "Jonathon Moore KC", "Dr Sue McNicol AM KC", "Nicholas Hopkins KC", "Nicholas Pane KC",
    "Dr Matt Collins AM KC", "Wendy Harris KC", "David Batt KC", "Warren Friend KC",
    "Albert Monichino KC", "Christopher Townshend KC", "Jeffery Gleeson KC", "Ian Martindale KC",
    "Tony Nolan KC", "Peter Collinson KC", "Graeme S. Clarke KC", "The Hon Michael Sifris KC",
    "Terry Murphy KC", "Julie Dodds-Streeton KC", "Manny Garantziotis KC", "Herman Borenstein KC",
    "Dr Richard Manly KC", "Jennifer Batrouney AM KC", "Peter Bick KC", "John de Wijn AM KC",
    "Michael Shand AM KC", "Neil Young KC", "Allan Myers AC KC", "Raymond Finkelstein AO KC",
    "Kenneth M Hayne AC KC",
  ],
};

export const COUNSEL_EMAILS_BY_NAME = {
  "Priyanka Banerjee": "priyanka@vicbar.com.au",
  "Katherine O'Byrne": "katie.obyrne@vicbar.com.au",
  "Samuel Hamilton Lindsay": "samuel.hamiltonlindsay@vicbar.com.au",
  "Dr Georgie Clough": "gclough@vicbar.com.au",
  "Rohan Nanthakumar": "r.nanthakumar@vicbar.com.au",
  "Katherine France": "kfrance@vicbar.com.au",
  "Selena Bateman": "sbateman@vicbar.com.au",
  "Beatrice Paull": "beatrice.paull@vicbar.com.au",
  "Ben Kelly": "ben.kelly@vicbar.com.au",
  "Andrew Belyea-Tate": "andrew.belyea-tate@vicbar.com.au",
  "Marcel Delany": "mdelany@vicbar.com.au",
  "Matthew Harding": "matthew.harding@vicbar.com.au",
  "Nuwan Dias": "nuwan.dias@vicbar.com.au",
  "Jennifer Vogan": "jennifer.vogan@vicbar.com.au",
  "Conor O'Beirne": "cob@vicbar.com.au",
  "Georgia Dobbyn": "georgia.dobbyn@vicbar.com.au",
  "Gary Zhang": "gary.zhang@vicbar.com.au",
  "Stephanie Mann": "smann@vicbar.com.au",
  "Tom Diaz": "tdiaz@vicbar.com.au",
  "Luke Chircop": "luke.chircop@vicbar.com.au",
  "Bernice Chen": "bernice.chen@vicbar.com.au",
  "Angela Kittikhoun": "angela.kittikhoun@vicbar.com.au",
  "Anesti Petridis": "anesti@vicbar.com.au",
  "Jessica Elliott": "jessica.elliott@vicbar.com.au",
  "Dr Laura Schuijers": "laura.schuijers@vicbar.com.au",
  "Marcus Roberts": "marcus.roberts@vicbar.com.au",
  "David Heaton": "david.heaton@vicbar.com.au",
  "Elodie Nadon": "elodie.nadon@vicbar.com.au",
  "Tom Ellicott": "tom.ellicott@vicbar.com.au",
  "Yanni Goutzamanis": "yanni.goutzamanis@vicbar.com.au",
  "Angus Willoughby": "angus.willoughby@vicbar.com.au",
  "Melinda Jackson": "melinda.jackson@vicbar.com.au",
  "Jakub Patela": "jakub.patela@vicbar.com.au",
  "Andy Hanna": "andy.hanna@vicbar.com.au",
  "Alissa Crittenden": "alissa.crittenden@vicbar.com.au",
  "Laila Hamzi": "laila.hamzi@vicbar.com.au",
  "Elizabeth Brumby": "elizabeth.brumby@vicbar.com.au",
  "Jack Maxwell": "jack.maxwell@vicbar.com.au",
  "Madeleine Salinger": "madeleine.salinger@vicbar.com.au",
  "Julia Nikolic": "julia.nikolic@vicbar.com.au",
  "Katharine Brown": "katharine.brown@vicbar.com.au",
  "Ahmed Terzic": "ahmed.terzic@vicbar.com.au",
  "Shawn Rajanayagam": "rajanayagam@vicbar.com.au",
  "Sophie Molyneux": "sophie.molyneux@vicbar.com.au",
  "Nicholas Baum": "nicholas.baum@vicbar.com.au",
  "Jacqui Fumberger": "jfumberger@vicbar.com.au",
  "Nicholas Petrie": "nicholas.petrie@vicbar.com.au",
  "Sahrah Hogan": "shogan@vicbar.com.au",
  "Alexander Di Stefano": "alexander.distefano@vicbar.com.au",
  "Anna Batrouney": "anna.batrouney@vicbar.com.au",
  "Jessica Moir": "jess.moir@vicbar.com.au",
  "Ben Bromberg": "ben.bromberg@vicbar.com.au",
  "Tessa Meyrick": "tessa.meyrick@vicbar.com.au",
  "Thomas Wood": "twood@vicbar.com.au",
  "Simon Frauenfelder": "frauenfelder@vicbar.com.au",
  "Glyn Ayres": "glyn.ayres@vicbar.com.au",
  "Alexandra Guild": "alexandra.guild@vicbar.com.au",
  "Rachel Amamoo": "rachel.amamoo@vicbar.com.au",
  "Ella Delany": "edelany@vicbar.com.au",
  "Joel Phillips": "joel.phillips@vicbar.com.au",
  "Karan Raghavan": "karan.raghavan@vicbar.com.au",
  "Caroline Dawes": "cjdawes@vicbar.com.au",
  "Paul Annabell": "paul.annabell@vicbar.com.au",
  "Andrew Roe": "andrew.roe@vicbar.com.au",
  "Jordan Wright": "jwright@vicbar.com.au",
  "Doug Porteous": "porteous@vicbar.com.au",
  "Claire Horan": "claire.horan@vicbar.com.au",
  "Vicki Bell": "vbell@vicbar.com.au",
  "Alexia Staker": "alexia.staker@vicbar.com.au",
  "Alice Muhlebach": "alice.muhlebach@vicbar.com.au",
  "Andrew McRobert": "mcrobert@vicbar.com.au",
  "Tim Farhall": "tim.farhall@vicbar.com.au",
  "Fiona Hudgson": "fiona.hudgson@vicbar.com.au",
  "William Newland": "william.newland@vicbar.com.au",
  "Xuelin Teo": "xteo@vicbar.com.au",
  "Anna Lord": "anna.lord@vicbar.com.au",
  "Tim Jeffrie": "tim.jeffrie@vicbar.com.au",
  "Adam Purton": "purton@vicbar.com.au",
  "Stephanie Hooper": "shooper@vicbar.com.au",
  "Franceska Leoncio": "franceska.leoncio@vicbar.com.au",
  "Roshan Chaile": "roshan.chaile@vicbar.com.au",
  "Mark Hosking": "mark.hosking@vicbar.com.au",
  "Roman Rozenberg": "rr@vicbar.com.au",
  "Geoffrey Kozminsky": "gkozminsky@vicbar.com.au",
  "Olaf Ciolek": "ciolek@vicbar.com.au",
  "Raini Zambelli": "zambelli@vicbar.com.au",
  "Timothy Goodwin": "tim.goodwin@vicbar.com.au",
  "Georgie Coleman": "gcoleman@vicbar.com.au",
  "Tim Chalke": "tim.chalke@vicbar.com.au",
  "Emma Murphy": "emma.murphy@vicbar.com.au",
  "Matthew Minucci": "matthewminucci@vicbar.com.au",
  "Christopher Tran": "christopher.tran@vicbar.com.au",
  "Timothy Maxwell": "tim.maxwell@vicbar.com.au",
  "Julia Watson": "juliawatson@vicbar.com.au",
  "Dimitri Ternovski": "d@ternovski.com",
  "Daniel Snyder": "daniel.snyder@vicbar.com.au",
  "Andrew Barraclough": "abarraclough@vicbar.com.au",
  "Katherine Brazenor": "brazenor@vicbar.com.au",
  "Brian Mason": "bmason@vicbar.com.au",
  "Simona Gory": "simona.gory@vicbar.com.au",
  "Leana Papaelia": "leana.papaelia@vicbar.com.au",
  "Fiona Batten": "fiona.batten@vicbar.com.au",
  "Caryn van Proctor": "vanproctor@vicbar.com.au",
  "Helen Tiplady": "helen.tiplady@vicbar.com.au",
  "Nasos Kaskani": "nasos.kaskani@vicbar.com.au",
  "Dr Philip Bender": "pbender@vicbar.com.au",
  "Rodrigo Pintos-Lopez": "rpintoslopez@vicbar.com.au",
  "Eloise Dias": "eloise.dias@vicbar.com.au",
  "Michael Kingston": "michael.kingston@vicbar.com.au",
  "St. John Hibble": "shibble@vicbar.com.au",
  "Chris Sievers": "csievers@vicbar.com.au",
  "Peter Nicholas": "pnicholas@vicbar.com.au",
  "Chrissy Mavroudis": "chrissy.mavroudis@vicbar.com.au",
  "Anthony Lang": "lang@vicbar.com.au",
  "Garrie Moloney": "gjmoloney@vicbar.com.au",
  "Warren Mosley": "mosley@vicbar.com.au",
  "Joseph Tsalanidis": "tsalanidis@vicbar.com.au",
  "Robert Strong": "robstrong@vicbar.com.au",
  "Peter Best": "besres@mail.com",
  "John Mattin": "johnmattin@vicbar.com.au",
  "Robert Williams SC": "robert.williams@vicbar.com.au",
  "Siobhan Kelly SC": "siobhan.kelly@vicbar.com.au",
  "Premala Thiagarajan SC": "premala@aickin.com.au",
  "Kylie Evans KC": "kylie.evans@vicbar.com.au",
  "Barnaby Chessell SC": "chessell@vicbar.com.au",
  "Christopher Brown KC": "cbrown@vicbar.com.au",
  "Tamieka Spencer Bruce SC": "tspencerbruce@vicbar.com.au",
  "Paul Liondas KC": "paul.liondas@vicbar.com.au",
  "Zoe Maud SC": "zoe.maud@vicbar.com.au",
  "Emrys Nekvapil SC": "emrys@vicbar.com.au",
  "Mark Costello KC": "mark.costello@vicbar.com.au",
  "Frances Gordon KC": "francesgordon@vicbar.com.au",
  "Sam Rosewarne KC": "srosewarne@vicbar.com.au",
  "Albert Dinelli KC": "albert.dinelli@vicbar.com.au",
  "Carl Möller SC": "cmoller@vicbar.com.au",
  "Emily Porter SC": "eporter@vicbar.com.au",
  "Dr Charles Parkinson KC": "cparkinson@vicbar.com.au",
  "Marc Felman KC": "marc.felman@vicbar.com.au",
  "Sandro Goubran KC": "sandro.goubran@vicbar.com.au",
  "Daniel McInerney KC": "mcinerney@vicbar.com.au",
  "Jonathon Redwood SC": "jonathon.redwood@banco.net.au",
  "Dr Paul Vout KC": "vout@vicbar.com.au",
  "Justin Graham KC": "justin.graham@vicbar.com.au",
  "Dr Oren Bigos KC": "oren.bigos@vicbar.com.au",
  "Renée Enbom KC": "renbom@vicbar.com.au",
  "Christopher Young KC": "chris.young@vicbar.com.au",
  "Dr Michael Rush KC": "michael.rush@vicbar.com.au",
  "Christopher Archibald KC": "cmarchibald@vicbar.com.au",
  "Lisa De Ferrari SC": "lisa.deferrari@vicbar.com.au",
  "Dr Andrew Hanak KC": "hanak@vicbar.com.au",
  "Stephen Parmenter KC": "stephenparmenter@vicbar.com.au",
  "Michael Borsky KC": "mborsky@vicbar.com.au",
  "Dan Star KC": "danstar@vicbar.com.au",
  "Andrew McClelland KC": "amcclelland@vicbar.com.au",
  "Lachlan Armstrong KC": "larmstrong@vicbar.com.au",
  "Jason Pizer SC": "pizer@vicbar.com.au",
  "Jonathon Moore KC": "jpmoore@vicbar.com.au",
  "Dr Sue McNicol AM KC": "smcnicol@vicbar.com.au",
  "Nicholas Hopkins KC": "ndhopkins@vicbar.com.au",
  "Nicholas Pane KC": "npane@vicbar.com.au",
  "Dr Matt Collins AM KC": "matt.collins@vicbar.com.au",
  "Wendy Harris KC": "harriswa@vicbar.com.au",
  "David Batt KC": "battdj@vicbar.com.au",
  "Warren Friend KC": "wlfriend@vicbar.com.au",
  "Albert Monichino KC": "albert@monichino.me",
  "Christopher Townshend KC": "ctownshend@vicbar.com.au",
  "Jeffery Gleeson KC": "gleeson@vicbar.com.au",
  "Ian Martindale KC": "ianmartindale@vicbar.com.au",
  "Tony Nolan KC": "anolan@vicbar.com.au",
  "Peter Collinson KC": "collinson@chancery.com.au",
  "Graeme S. Clarke KC": "gsclarke@vicbar.com.au",
  "The Hon Michael Sifris KC": "m.sifris@vicbar.com.au",
  "Terry Murphy KC": "murphy@chancery.com.au",
  "Manny Garantziotis KC": "manny@vicbar.com.au",
  "Herman Borenstein KC": "h.borenstein@vicbar.com.au",
  "Dr Richard Manly KC": "manly@chancery.com.au",
  "Jennifer Batrouney AM KC": "jennifer_batrouney@vicbar.com.au",
  "Peter Bick KC": "bickp@vicbar.com.au",
  "John de Wijn AM KC": "dewijn@vicbar.com.au",
  "Michael Shand AM KC": "mwshand@vicbar.com.au",
  "Neil Young KC": "njyoung@vicbar.com.au",
  "Allan Myers AC KC": "ajmyers@dunkeldpastoral.com.au",
  "Raymond Finkelstein AO KC": "rayfinkelstein@vicbar.com.au",
  "Kenneth M Hayne AC KC": "kmhayne@vicbar.com.au",
};

export const COUNSEL_LIST = [];

export const COUNSEL_EMAILS = [];

// Fee lists per court type
export const CHILDRENS_COURT_FEES = [
  // Bail
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Contested bail preparation", amount: 226 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "First remand hearing", amount: 231 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Bail appearance fee", amount: 484 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Intensive Bail Scheme supervision hearings", amount: 185 },
  // Summary
  { group: "SUMMARY PROCEEDINGS", label: "Lump sum general preparation fee", amount: 484 },
  { group: "SUMMARY PROCEEDINGS", label: "Lump sum preparation fee (urgent matter)", amount: 277 },
  { group: "SUMMARY PROCEEDINGS", label: "Lump sum consolidated preparation fee", amount: 579 },
  { group: "SUMMARY PROCEEDINGS", label: "Lump sum consolidated preparation fee (urgent matter)", amount: 348 },
  { group: "SUMMARY PROCEEDINGS", label: "Contest mention", amount: 332 },
  { group: "SUMMARY PROCEEDINGS", label: "Consol contest mention", amount: 581 },
  { group: "SUMMARY PROCEEDINGS", label: "Contest hearing appearance (whether or not the matter proceeds as a contest)", amount: 1099 },
  { group: "SUMMARY PROCEEDINGS", label: "Daily appearance fee", amount: 484 },
  { group: "SUMMARY PROCEEDINGS", label: "Daily appearance fee (consolidation)", amount: 579 },
  { group: "SUMMARY PROCEEDINGS", label: "Appearance on sentence or adjournment", amount: 318 },
  { group: "SUMMARY PROCEEDINGS", label: "Appearance on sentence or adjournment (consolidation)", amount: 369 },
  { group: "SUMMARY PROCEEDINGS", label: "Group conference held during work hours", amount: 464 },
  { group: "SUMMARY PROCEEDINGS", label: "Group conference held outside work hours", amount: 594 },
  { group: "SUMMARY PROCEEDINGS", label: "Youth Control Order planning meeting", amount: 358 },
  { group: "SUMMARY PROCEEDINGS", label: "Youth Control Order reporting and monitoring hearing, including variation to a less restrictive order", amount: 185 },
  { group: "SUMMARY PROCEEDINGS", label: "Youth Control Order reporting and monitoring hearing to oppose a variation to a significantly more restrictive order", amount: 318 },
  { group: "SUMMARY PROCEEDINGS", label: "Breach or Revocation of a Youth Control Order", amount: 484 },
  { group: "SUMMARY PROCEEDINGS", label: "Application for summary jurisdiction", amount: 445 },
  { group: "SUMMARY PROCEEDINGS", label: "Plea heard at contest mention – contest mention fee", amount: 332 },
  { group: "SUMMARY PROCEEDINGS", label: "Plea heard at contest mention – contest mention fee (consolidation)", amount: 581 },
  { group: "SUMMARY PROCEEDINGS", label: "Plea heard at contest mention – plea fee", amount: 318 },
  { group: "SUMMARY PROCEEDINGS", label: "Plea heard at contest mention – plea fee (consolidation)", amount: 369 },
  { group: "SUMMARY PROCEEDINGS", label: "Transcribing of taped record of interview, if necessary", amount: 99 },
  // Indictable matters
  { group: "INDICTABLE MATTERS", label: "General preparation fee", amount: 712 },
  { group: "INDICTABLE MATTERS", label: "Brief analysis and case strategy fee", amount: 712 },
  { group: "INDICTABLE MATTERS", label: "Additional preparation (contested committal/negotiations)", amount: 890 },
  { group: "INDICTABLE MATTERS", label: "Committal mention", amount: 445 },
  { group: "INDICTABLE MATTERS", label: "Case Conference", amount: 445 },
  { group: "INDICTABLE MATTERS", label: "Summary Jurisdiction Application", amount: 445 },
  { group: "INDICTABLE MATTERS", label: "Application for leave to XXN witnesses", amount: 445 },
  { group: "INDICTABLE MATTERS", label: "Ground rules hearing (daily appearance fee)", amount: 484 },
  { group: "INDICTABLE MATTERS", label: "Special mention", amount: 178 },
  { group: "INDICTABLE MATTERS", label: "Appearance on contested committal: day 1", amount: 1284 },
  { group: "INDICTABLE MATTERS", label: "Appearance on contested committal: day 2", amount: 1157 },
  { group: "INDICTABLE MATTERS", label: "Plea after Committal", amount: 537 },
  { group: "INDICTABLE MATTERS", label: "Plea after Summary Jurisdiction application", amount: 537 },
  { group: "INDICTABLE MATTERS", label: "Sentence fee", amount: 318 },
  // Serious indictable crime
  { group: "SERIOUS INDICTABLE CRIME", label: "Prep", amount: 719 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Contest mention", amount: 356 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Appearance fee", amount: 1214 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Application for summary jurisdiction", amount: 445 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Group conference held during work hours", amount: 534 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Group conference held after work hours", amount: 712 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Youth Control Order planning meeting", amount: 358 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Youth Control Order reporting and monitoring hearing, including variation to a less restrictive order", amount: 185 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Youth Control Order reporting and monitoring hearing to oppose a variation to a significantly more restrictive order", amount: 318 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Breach or Revocation of a Youth Control Order", amount: 484 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Sentence (if on a different day)", amount: 358 },
  { group: "SERIOUS INDICTABLE CRIME", label: "Transcribing of taped record of interview, if necessary", amount: 99 },
];

export const MAGISTRATES_COURT_FEES = [
  // Summary Matters
  { group: "SUMMARY MATTERS", label: "Prep", amount: 484 },
  { group: "SUMMARY MATTERS", label: "Prep (urgent matter)", amount: 277 },
  { group: "SUMMARY MATTERS", label: "Consol prep", amount: 579 },
  { group: "SUMMARY MATTERS", label: "Consol prep (urgent)", amount: 348 },
  { group: "SUMMARY MATTERS", label: "Transcribing of taped record of interview, if necessary", amount: 99 },
  { group: "SUMMARY MATTERS", label: "Contest Mention", amount: 332 },
  { group: "SUMMARY MATTERS", label: "Consol Contest Mention", amount: 581 },
  { group: "SUMMARY MATTERS", label: "Contest hearing appearance", amount: 1099 },
  { group: "SUMMARY MATTERS", label: "Daily appearance fee", amount: 484 },
  { group: "SUMMARY MATTERS", label: "Daily appearance fee (consolidation)", amount: 579 },
  { group: "SUMMARY MATTERS", label: "Appearance on sentence or adjournment", amount: 318 },
  { group: "SUMMARY MATTERS", label: "Appearance on sentence or adjournment (consolidation)", amount: 369 },
  { group: "SUMMARY MATTERS", label: "Plea heard at contest mention – plea fee", amount: 318 },
  { group: "SUMMARY MATTERS", label: "Plea heard at contest mention – plea fee (consolidation)", amount: 369 },
  { group: "SUMMARY MATTERS", label: "Court Integrated Services Program/Drug Court mention", amount: 185 },
  { group: "SUMMARY MATTERS", label: "Assessment and Referral Court – Individual Support Plan Ratification hearing", amount: 332 },
  { group: "SUMMARY MATTERS", label: "ARC Review Hearing", amount: 185 },
  { group: "SUMMARY MATTERS", label: "Special Mention", amount: 185 },
  { group: "SUMMARY MATTERS", label: "Sentence Indication", amount: 484 },
  { group: "SUMMARY MATTERS", label: "Sentence Indication Consol", amount: 581 },
  { group: "SUMMARY MATTERS", label: "FOI/Title Lodge/Search fee", amount: 668 },
  { group: "SUMMARY MATTERS", label: "Service/Filing/Conduct Money", amount: 617 },
  { group: "SUMMARY MATTERS", label: "First Remand hearing", amount: 231 },
  // Bail Fees
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Contested bail preparation", amount: 226 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "First remand hearing", amount: 231 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Appearance fee", amount: 484 },
  // Indictable Matters
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "General preparation fee", amount: 712 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Brief analysis and case strategy fee", amount: 712 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Additional preparation (contested committal/negotiations)", amount: 890 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Committal mention", amount: 445 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Case Conference", amount: 445 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Summary Jurisdiction Application", amount: 445 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Application for leave to XXN witnesses", amount: 445 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Ground rules hearing (daily appearance fee)", amount: 484 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Special mention", amount: 178 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Appearance on contested committal: day 1", amount: 1284 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Appearance on contested committal: day 2", amount: 1157 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Plea after Committal", amount: 537 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Plea after Summary Jurisdiction application", amount: 537 },
  { group: "INDICTABLE MATTERS HEARD IN THE MAGISTRATES COURT", label: "Sentence fee", amount: 318 },
  // Infringements
  { group: "INFRINGEMENTS", label: "Preparation", amount: 431 },
  { group: "INFRINGEMENTS", label: "Urgent Prep", amount: 247 },
  { group: "INFRINGEMENTS", label: "Appearance", amount: 431 },
  { group: "INFRINGEMENTS", label: "Urgent Appearance", amount: 431 },
  { group: "INFRINGEMENTS", label: "Adjournment (if assisted person requests, VLA approved)", amount: 285 },
  // Personal Safety / Family Violence Intervention Orders
  { group: "PERSONAL SAFETY/FAMILY VIOLENCE INTERVENTION ORDERS", label: "Lump sum preparation fee (covers all necessary work)", amount: 431 },
  { group: "PERSONAL SAFETY/FAMILY VIOLENCE INTERVENTION ORDERS", label: "Lump sum preparation fee (urgent matter)", amount: 247 },
  { group: "PERSONAL SAFETY/FAMILY VIOLENCE INTERVENTION ORDERS", label: "Directions hearing", amount: 161 },
  { group: "PERSONAL SAFETY/FAMILY VIOLENCE INTERVENTION ORDERS", label: "Appearance fee", amount: 431 },
  { group: "PERSONAL SAFETY/FAMILY VIOLENCE INTERVENTION ORDERS", label: "Contest appearance fee (matter proceeds to contested hearing by way of evidence)", amount: 605 },
  { group: "PERSONAL SAFETY/FAMILY VIOLENCE INTERVENTION ORDERS", label: "Adjournment fee (court ordered VLA to fund cross-examination)", amount: 431 },
];

export const COUNTY_COURT_FEES = [
  // Bail
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Prep", amount: 1030 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Appearance fee", amount: 968 },
  { group: "BAIL FEES - APPLICATION/VARIATION/REVOCATION", label: "Mention/adjournment fee", amount: 298 },
  // General fees
  { group: "GENERAL FEES", label: "Counsel – post-committal negotiations", amount: 714 },
  { group: "GENERAL FEES", label: "First directions hearing", amount: 476 },
  { group: "GENERAL FEES", label: "Directions hearing/mention/call over", amount: 297 },
  { group: "GENERAL FEES", label: "Defence response – first directions hearing", amount: 476 },
  { group: "GENERAL FEES", label: "Application for discontinuance or proceedings", amount: 595 },
  // Plea fees
  { group: "PLEA FEES", label: "Preparation", amount: 561 },
  { group: "PLEA FEES", label: "Appearance fee – first day (includes conferences)", amount: 1834 },
  { group: "PLEA FEES", label: "Appearance fee – subsequent day(s)", amount: 638 },
  { group: "PLEA FEES", label: "Sentence", amount: 356 },
  { group: "PLEA FEES", label: "Advice on appeal", amount: 326 },
  // Special hearing
  { group: "SPECIAL HEARING", label: "Preparation", amount: 187 },
  { group: "SPECIAL HEARING", label: "Appearance fee – first day (includes conferences)", amount: 2501 },
  { group: "SPECIAL HEARING", label: "Appearance fee – subsequent day(s)", amount: 1370 },
  // Sentence indication
  { group: "SENTENCE INDICATION", label: "Appearance fee (includes conferences)", amount: 1350 },
  { group: "SENTENCE INDICATION", label: "Subsequent day fee (if indication not accepted, matter adjourned)", amount: 638 },
  // Intermediaries/ground rules hearings
  { group: "INTERMEDIARIES/GROUND RULES HEARINGS", label: "Ground rules hearing", amount: 1370 },
  // Section 198A hearings
  { group: "SECTION 198A HEARINGS", label: "Application for hearing", amount: 714 },
  { group: "SECTION 198A HEARINGS", label: "Pre-trial examination", amount: 1370 },
  // Active Case Management System
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Case Initiation Notice", amount: 476 },
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Preparation for case conference (instructor)", amount: 714 },
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Counsel - preparation for case conference", amount: 1612 },
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Appearance at case conference", amount: 1370 },
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Instructing – per hour (up to maximum of 5 hours per day)", amount: 165 },
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Trial Readiness Questionnaire Certificate", amount: 473 },
  { group: "ACTIVE CASE MANAGEMENT SYSTEM", label: "Case assessment hearing", amount: 596 },
  // Trial
  { group: "TRIAL", label: "Preparation", amount: 1870 },
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 476 },
  { group: "TRIAL", label: "Appearance fee – first day (includes conferences) [junior]", amount: 2982 },
  { group: "TRIAL", label: "Appearance fee – first day (includes conferences) [senior]", amount: 3578 },
  { group: "TRIAL", label: "Appearance fee – subsequent day(s)", amount: 1370 },
  { group: "TRIAL", label: "Instructing – per hour (up to maximum of 5 hours per day)", amount: 165 },
  { group: "TRIAL", label: "Plea hearing – first day", amount: 1106 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 638 },
  { group: "TRIAL", label: "Sentence", amount: 356 },
  { group: "TRIAL", label: "Advice on appeal", amount: 978 },
  // County Court Appeals - Sentence
  { group: "COUNTY COURT APPEALS - SENTENCE", label: "Prep", amount: 1030 },
  { group: "COUNTY COURT APPEALS - SENTENCE", label: "Appearance fee", amount: 968 },
  { group: "COUNTY COURT APPEALS - SENTENCE", label: "Appearance to hear sentence", amount: 356 },
  { group: "COUNTY COURT APPEALS - SENTENCE", label: "Mention/adjournment fee", amount: 298 },
  // County Court Appeals - Sentence and Conviction
  { group: "COUNTY COURT APPEALS - SENTENCE AND CONVICTION", label: "Solicitor preparation", amount: 1028 },
  { group: "COUNTY COURT APPEALS - SENTENCE AND CONVICTION", label: "Mention", amount: 297 },
  { group: "COUNTY COURT APPEALS - SENTENCE AND CONVICTION", label: "Daily appearance", amount: 1087 },
  { group: "COUNTY COURT APPEALS - SENTENCE AND CONVICTION", label: "Sentence", amount: 356 },
  // County Court Breach/Variation
  { group: "COUNTY COURT BREACH/VARIATION", label: "Solicitor preparation", amount: 1028 },
  { group: "COUNTY COURT BREACH/VARIATION", label: "Mention", amount: 297 },
  { group: "COUNTY COURT BREACH/VARIATION", label: "Daily appearance", amount: 1087 },
  { group: "COUNTY COURT BREACH/VARIATION", label: "Sentence (if on a different day)", amount: 356 },
  // CMIA
  { group: "CMIA", label: "Preparation", amount: 1496 },
  { group: "CMIA", label: "Appearance fee - first day", amount: 2982 },
  { group: "CMIA", label: "Appearance fee - subsequent day(s)", amount: 1370 },
  { group: "CMIA", label: "Mention fee", amount: 297 },
  { group: "CMIA", label: "Judgement", amount: 356 },
  { group: "CMIA", label: "Instructing - per hour", amount: 165 },
  // Supervision orders
  { group: "SUPERVISION ORDERS / COMMONWEALTH EXTENDED SUPERVISION ORDERS OR CONTROL ORDERS", label: "Lump sum (preparation)", amount: 935 },
  { group: "SUPERVISION ORDERS / COMMONWEALTH EXTENDED SUPERVISION ORDERS OR CONTROL ORDERS", label: "Brief (includes conferences)", amount: 2501 },
  { group: "SUPERVISION ORDERS / COMMONWEALTH EXTENDED SUPERVISION ORDERS OR CONTROL ORDERS", label: "Subsequent days", amount: 1370 },
  { group: "SUPERVISION ORDERS / COMMONWEALTH EXTENDED SUPERVISION ORDERS OR CONTROL ORDERS", label: "Mention/directions", amount: 298 },
  { group: "SUPERVISION ORDERS / COMMONWEALTH EXTENDED SUPERVISION ORDERS OR CONTROL ORDERS", label: "Instructing – per hour (up to a maximum of 5 hours per day)", amount: 165 },
  { group: "SUPERVISION ORDERS / COMMONWEALTH EXTENDED SUPERVISION ORDERS OR CONTROL ORDERS", label: "Judgement fee", amount: 356 },
  // Application for review
  { group: "APPLICATION FOR REVIEW BROUGHT BY A PERSON SUBJECT TO AN ORDER", label: "Lump sum (preparation)", amount: 935 },
  { group: "APPLICATION FOR REVIEW BROUGHT BY A PERSON SUBJECT TO AN ORDER", label: "Daily appearance fee", amount: 1087 },
  { group: "APPLICATION FOR REVIEW BROUGHT BY A PERSON SUBJECT TO AN ORDER", label: "Mention/directions", amount: 298 },
  { group: "APPLICATION FOR REVIEW BROUGHT BY A PERSON SUBJECT TO AN ORDER", label: "Judgement fee", amount: 356 },
];

export const SUPREME_COURT_FEES = [
  { group: "BAIL", label: "Bail Application", amount: 893 },
  { group: "PLEA", label: "Preparation fee (Plea)", amount: 1819 },
  { group: "PLEA", label: "Plea of guilty - day 1", amount: 1819 },
  { group: "PLEA", label: "Plea of guilty - subsequent day", amount: 1637 },
  { group: "TRIAL", label: "Preparation fee (Trial)", amount: 3638 },
  { group: "TRIAL", label: "Trial - day 1", amount: 3638 },
  { group: "TRIAL", label: "Trial - subsequent day", amount: 2912 },
  { group: "APPEAL", label: "Preparation fee (Appeal)", amount: 1819 },
  { group: "APPEAL", label: "Appeal - day 1", amount: 1819 },
  { group: "APPEAL", label: "Appeal - subsequent day", amount: 1637 },
  { group: "OTHER", label: "Directions hearing", amount: 630 },
  { group: "OTHER", label: "Special mention", amount: 473 },
];

export const GENERIC_FEES = [
  { group: "APPEARANCES", label: "Appearance", amount: 473 },
  { group: "APPEARANCES", label: "Directions hearing", amount: 473 },
  { group: "APPEARANCES", label: "Special mention", amount: 311 },
];

export const SUPREME_COURT_SENIOR_COUNSEL_FEES = [
  { group: "POST COMMITTAL", label: "Post-committal negotiations", amount: 1308 },
  { group: "POST COMMITTAL", label: "First directions hearing", amount: 872 },
  { group: "POST COMMITTAL", label: "Directions hearing/mention/callover", amount: 545 },
  { group: "POST COMMITTAL", label: "Defence response – first directions hearing", amount: 872 },
  { group: "POST COMMITTAL", label: "Application for discontinuance of proceedings", amount: 1090 },
  { group: "PLEA FEES", label: "Brief fee – first day (includes conferences)", amount: 4025 },
  { group: "PLEA FEES", label: "Subsequent day", amount: 2240 },
  { group: "PLEA FEES", label: "Sentence (if on a different day)", amount: 661 },
  { group: "SPECIAL HEARING", label: "Brief fee – first day (includes conferences)", amount: 4934 },
  { group: "SPECIAL HEARING", label: "Subsequent day", amount: 3364 },
  { group: "SENTENCE INDICATION", label: "Brief fee (includes conferences)", amount: 3138 },
  { group: "SENTENCE INDICATION", label: "Subsequent day", amount: 2240 },
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 872 },
  { group: "TRIAL", label: "Brief fee – first day (includes conferences)", amount: 7149 },
  { group: "TRIAL", label: "Brief fee – first day where 20% uplift applicable (includes conferences)", amount: 8578 },
  { group: "TRIAL", label: "Subsequent day", amount: 3364 },
  { group: "TRIAL", label: "Plea hearing", amount: 2694 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 2240 },
  { group: "TRIAL", label: "Sentence (if on different day)", amount: 661 },
  { group: "TRIAL", label: "Conference with junior counsel (Trial Counsel Development Program only)", amount: 1308 },
];

export const SUPREME_COURT_SENIOR_JUNIOR_COUNSEL_FEES = [
  { group: "POST COMMITTAL", label: "Post-committal negotiations", amount: 978 },
  { group: "POST COMMITTAL", label: "First directions hearing", amount: 652 },
  { group: "POST COMMITTAL", label: "Directions hearing/mention/callover", amount: 407 },
  { group: "POST COMMITTAL", label: "Defence response – first directions hearing", amount: 652 },
  { group: "POST COMMITTAL", label: "Application for discontinuance of proceedings", amount: 815 },
  { group: "PLEA FEES", label: "Brief fee – first day (includes conferences)", amount: 2504 },
  { group: "PLEA FEES", label: "Subsequent day", amount: 1002 },
  { group: "PLEA FEES", label: "Sentence (if on a different day)", amount: 491 },
  { group: "SPECIAL HEARING", label: "Brief fee – first day (includes conferences)", amount: 3410 },
  { group: "SPECIAL HEARING", label: "Subsequent day", amount: 2197 },
  { group: "SENTENCE INDICATION", label: "Brief fee (includes conferences)", amount: 1838 },
  { group: "SENTENCE INDICATION", label: "Subsequent day", amount: 1002 },
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 652 },
  { group: "TRIAL", label: "Brief fee – first day (includes conferences)", amount: 4737 },
  { group: "TRIAL", label: "Brief fee – first day where 20% uplift applicable (includes conferences)", amount: 5684 },
  { group: "TRIAL", label: "Subsequent day", amount: 2197 },
  { group: "TRIAL", label: "Plea hearing", amount: 1508 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 1002 },
  { group: "TRIAL", label: "Sentence (if on different day)", amount: 491 },
  { group: "TRIAL", label: "Conference with junior counsel (Trial Counsel Development Program only)", amount: 978 },
];

export const SUPREME_COURT_JUNIOR_COUNSEL_FEES = [
  { group: "POST COMMITTAL", label: "Post-committal negotiations", amount: 495 },
  { group: "POST COMMITTAL", label: "First directions hearing", amount: 330 },
  { group: "POST COMMITTAL", label: "Directions hearing/mention/callover", amount: 206 },
  { group: "POST COMMITTAL", label: "Defence response – first directions hearing", amount: 330 },
  { group: "POST COMMITTAL", label: "Application for discontinuance of proceedings", amount: 412 },
  { group: "PLEA FEES", label: "Brief fee – first day (includes conferences)", amount: 1395 },
  { group: "PLEA FEES", label: "Subsequent day", amount: 735 },
  { group: "PLEA FEES", label: "Sentence (if on a different day)", amount: 491 },
  { group: "SPECIAL HEARING", label: "Brief fee – first day (includes conferences)", amount: 1666 },
  { group: "SPECIAL HEARING", label: "Subsequent day", amount: 1091 },
  { group: "SENTENCE INDICATION", label: "Brief fee (includes conferences)", amount: 1045 },
  { group: "SENTENCE INDICATION", label: "Subsequent day", amount: 735 },
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 330 },
  { group: "TRIAL", label: "Brief fee – first day (includes conferences)", amount: 2524 },
  { group: "TRIAL", label: "Brief fee – first day where 20% uplift applicable (includes conferences)", amount: 3028 },
  { group: "TRIAL", label: "Subsequent day", amount: 1091 },
  { group: "TRIAL", label: "Plea hearing", amount: 880 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 735 },
  { group: "TRIAL", label: "Sentence (if on different day)", amount: 491 },
  { group: "TRIAL", label: "Conference with senior/lead counsel (Trial Counsel Development Program only)", amount: 495 },
];

export const COUNTY_COURT_JUNIOR_COUNSEL_FEES = [
  // Post committal
  { group: "POST COMMITTAL", label: "Post-committal negotiations", amount: 438 },
  { group: "POST COMMITTAL", label: "First directions hearing", amount: 292 },
  { group: "POST COMMITTAL", label: "Directions hearing/mention/callover", amount: 182 },
  { group: "POST COMMITTAL", label: "Defence response – first directions hearing", amount: 292 },
  { group: "POST COMMITTAL", label: "Application for discontinuance of proceedings", amount: 365 },
  // Plea fees
  { group: "PLEA FEES", label: "Brief fee – first day (includes conferences)", amount: 1086 },
  { group: "PLEA FEES", label: "Subsequent day", amount: 501 },
  { group: "PLEA FEES", label: "Sentence (if on a different day)", amount: 356 },
  // Special hearing
  { group: "SPECIAL HEARING", label: "Brief fee – first day (includes conferences)", amount: 1249 },
  { group: "SPECIAL HEARING", label: "Subsequent day", amount: 754 },
  // Sentence indication
  { group: "SENTENCE INDICATION", label: "Brief fee (includes conferences)", amount: 780 },
  { group: "SENTENCE INDICATION", label: "Subsequent day", amount: 501 },
  // Trial
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 292 },
  { group: "TRIAL", label: "Brief fee – first day (includes conferences)", amount: 1403 },
  { group: "TRIAL", label: "Brief fee – first day where 20% uplift applicable (includes conferences)", amount: 1682 },
  { group: "TRIAL", label: "Subsequent day", amount: 754 },
  { group: "TRIAL", label: "Plea hearing", amount: 628 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 501 },
  { group: "TRIAL", label: "Sentence (if on different day)", amount: 356 },
  { group: "TRIAL", label: "Conference with senior/lead counsel (Trial Counsel Development Program only)", amount: 438 },
];

export const COUNTY_COURT_SENIOR_JUNIOR_COUNSEL_FEES = [
  // Post committal
  { group: "POST COMMITTAL", label: "Post-committal negotiations", amount: 714 },
  { group: "POST COMMITTAL", label: "First directions hearing", amount: 476 },
  { group: "POST COMMITTAL", label: "Directions hearing/mention/callover", amount: 297 },
  { group: "POST COMMITTAL", label: "Defence response – first directions hearing", amount: 476 },
  { group: "POST COMMITTAL", label: "Application for discontinuance of proceedings", amount: 595 },
  // Plea fees
  { group: "PLEA FEES", label: "Brief fee – first day (includes conferences)", amount: 1834 },
  { group: "PLEA FEES", label: "Subsequent day", amount: 638 },
  { group: "PLEA FEES", label: "Sentence (if on a different day)", amount: 356 },
  // Special hearing
  { group: "SPECIAL HEARING", label: "Brief fee – first day (includes conferences)", amount: 2501 },
  { group: "SPECIAL HEARING", label: "Subsequent day", amount: 1370 },
  // Sentence indication
  { group: "SENTENCE INDICATION", label: "Brief fee (includes conferences)", amount: 1350 },
  { group: "SENTENCE INDICATION", label: "Subsequent day", amount: 638 },
  // Trial
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 476 },
  { group: "TRIAL", label: "Brief fee – first day (includes conferences)", amount: 2982 },
  { group: "TRIAL", label: "Brief fee – first day where 20% uplift applicable (includes conferences)", amount: 3578 },
  { group: "TRIAL", label: "Subsequent day", amount: 1370 },
  { group: "TRIAL", label: "Plea hearing", amount: 1106 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 638 },
  { group: "TRIAL", label: "Sentence (if on different day)", amount: 356 },
  { group: "TRIAL", label: "Conference with junior counsel (Trial Counsel Development Program only)", amount: 714 },
];

export const COUNTY_COURT_SENIOR_COUNSEL_FEES = [
  // Post committal
  { group: "POST COMMITTAL", label: "Post-committal negotiations", amount: 1308 },
  { group: "POST COMMITTAL", label: "First directions hearing", amount: 872 },
  { group: "POST COMMITTAL", label: "Directions hearing/mention/callover", amount: 545 },
  { group: "POST COMMITTAL", label: "Defence response – first directions hearing", amount: 872 },
  { group: "POST COMMITTAL", label: "Application for discontinuance of proceedings", amount: 1090 },
  // Plea fees
  { group: "PLEA FEES", label: "Brief fee – first day (includes conferences)", amount: 4025 },
  { group: "PLEA FEES", label: "Subsequent day", amount: 2240 },
  { group: "PLEA FEES", label: "Sentence (if on a different day)", amount: 661 },
  // Special hearing
  { group: "SPECIAL HEARING", label: "Brief fee – first day (includes conferences)", amount: 4934 },
  { group: "SPECIAL HEARING", label: "Subsequent day", amount: 3364 },
  // Sentence indication
  { group: "SENTENCE INDICATION", label: "Brief fee (includes conferences)", amount: 3138 },
  { group: "SENTENCE INDICATION", label: "Subsequent day", amount: 2240 },
  // Trial
  { group: "TRIAL", label: "Defence response – final directions hearing", amount: 872 },
  { group: "TRIAL", label: "Brief fee – first day (includes conferences)", amount: 6264 },
  { group: "TRIAL", label: "Brief fee – first day where 20% uplift applicable (includes conferences)", amount: 7516 },
  { group: "TRIAL", label: "Subsequent day", amount: 3364 },
  { group: "TRIAL", label: "Plea hearing", amount: 2694 },
  { group: "TRIAL", label: "Plea hearing – subsequent days", amount: 2240 },
  { group: "TRIAL", label: "Sentence (if on different day)", amount: 661 },
  { group: "TRIAL", label: "Conference with junior counsel (Trial Counsel Development Program only)", amount: 1308 },
];

export function getFeesForCourtType(courtType, counselRates) {
  if (courtType === "COUNTY COURT" && counselRates === "Senior Counsel") return COUNTY_COURT_SENIOR_COUNSEL_FEES;
  if (courtType === "COUNTY COURT" && counselRates === "Senior Junior Counsel") return COUNTY_COURT_SENIOR_JUNIOR_COUNSEL_FEES;
  if (courtType === "COUNTY COURT" && counselRates === "Junior/TCDP") return COUNTY_COURT_JUNIOR_COUNSEL_FEES;
  if (courtType === "SUPREME COURT" && counselRates === "Senior Counsel") return SUPREME_COURT_SENIOR_COUNSEL_FEES;
  if (courtType === "SUPREME COURT" && counselRates === "Senior Junior Counsel") return SUPREME_COURT_SENIOR_JUNIOR_COUNSEL_FEES;
  if (courtType === "SUPREME COURT" && counselRates === "Junior/TCDP") return SUPREME_COURT_JUNIOR_COUNSEL_FEES;
  switch (courtType) {
    case "CHILDRENS COURT": return CHILDRENS_COURT_FEES;
    case "MAGISTRATES COURT": return MAGISTRATES_COURT_FEES;
    case "COUNTY COURT": return COUNTY_COURT_FEES;
    case "SUPREME COURT": return SUPREME_COURT_FEES;
    default: return GENERIC_FEES;
  }
}